#!/bin/bash
# Command to make an nginx server listen on port 80
apt-get update
apt-get install nginx -y
ufw allow 'Nginx HTTP'
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
systemctl start nginx
systemctl enable nginx
lsof -i :80 | grep nginx > /dev/null
