#!/usr/bin/env bash
# prints the message infinity and beyond for
# eternity unless it is killed, not so ethernal after all :)

# Handle SIGTERM
trap "echo 'I am invincible!!!\n'" 15

# Print the message forever

while true;
do
    printf "To infinity and beyond\n";
    sleep 2
done
