#!/usr/bin/env bash
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

count=1

while [ $count -le 20 ];
do
    echo "$count"
    if [ $count -eq 4 ];
    then
        echo "bad luck from China"
    elif [ $count -eq 9 ];
    then 
        echo "bad luck from Japan"
    elif [ $count -eq 17 ];
    then
        echo "bad luck from Italy"
    fi
    (( count++ ))
done